version: '3.8'

services:
  ai-agent:
    build:
      context: .
      network: host
    container_name: ai_intelligence_agent
    restart: always
    dns:
      - 8.8.8.8
      - 114.114.114.114
    env_file:
      - .env
    volumes:
      - .:/app
